CREATE TABLE IF NOT EXISTS  baptism (
	id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY ,
	date  INT(11), 
	member  varchar(32)  DEFAULT '' NOT NULL, 
	ff_name  varchar(256)  DEFAULT '' NOT NULL, 
	fl_name  varchar(256)  DEFAULT '' NOT NULL, 
	father_religion  varchar(256)  DEFAULT '' NOT NULL, 
	father_phone  varchar(256)  DEFAULT '' NOT NULL, 
	father_email  varchar(256)  DEFAULT '' NOT NULL, 
	father_address  text  , 
	mf_name  varchar(256)  DEFAULT '' NOT NULL, 
	ml_name  varchar(256)  DEFAULT '' NOT NULL, 
	mother_religion  varchar(256)  DEFAULT '' NOT NULL, 
	mother_phone  varchar(256)  DEFAULT '' NOT NULL, 
	mother_email  varchar(256)  DEFAULT '' NOT NULL, 
	mother_address  text  , 
	gff_name  varchar(256)  DEFAULT '' NOT NULL, 
	gfl_name  varchar(256)  DEFAULT '' NOT NULL, 
	gf_age  varchar(256)  DEFAULT '' NOT NULL, 
	gf_phone  varchar(256)  DEFAULT '' NOT NULL, 
	gf_address  text  , 
	gmf_name  varchar(256)  DEFAULT '' NOT NULL, 
	gml_name  varchar(256)  DEFAULT '' NOT NULL, 
	gm_age  varchar(256)  DEFAULT '' NOT NULL, 
	gm_phone  varchar(256)  DEFAULT '' NOT NULL, 
	gm_address  varchar(256)  DEFAULT '' NOT NULL, 
	description  text  , 
	created_by INT(11), 
	modified_by INT(11), 
	created_on INT(11) , 
	modified_on INT(11) 
	) ENGINE=InnoDB  DEFAULT CHARSET=utf8;